import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-tertiary": "#452b00",
        "surface-container-lowest": "#0b0d1a",
        "on-surface": "#e1e1f4",
        "error-container": "#93000a",
        "on-secondary-fixed": "#001f27",
        "on-tertiary-fixed-variant": "#633f00",
        "on-error-container": "#ffdad6",
        "on-secondary": "#003642",
        "error": "#ffb4ab",
        "on-error": "#690005",
        "primary-container": "#7b2fff",
        "secondary-fixed-dim": "#3cd7ff",
        "on-secondary-fixed-variant": "#004e5f",
        "primary-fixed": "#eaddff",
        "on-surface-variant": "#ccc3d9",
        "outline": "#958da2",
        "tertiary-fixed": "#ffddb4",
        "primary-fixed-dim": "#d1bcff",
        "secondary-container": "#00d2fd",
        "on-tertiary-container": "#ffe1be",
        "surface-container-high": "#272937",
        "secondary-fixed": "#b4ebff",
        "outline-variant": "#4a4456",
        "on-primary": "#3d0090",
        "primary": "#d1bcff",
        "on-background": "#e1e1f4",
        "on-tertiary-fixed": "#291800",
        "surface-container-highest": "#323442",
        "inverse-on-surface": "#2e2f3e",
        "on-secondary-container": "#005669",
        "tertiary-container": "#8e5c00",
        "surface-bright": "#373847",
        "tertiary-fixed-dim": "#ffb955",
        "surface-container-low": "#191b28",
        "inverse-surface": "#e1e1f4",
        "surface-variant": "#323442",
        "on-primary-fixed": "#24005b",
        "on-primary-container": "#ede1ff",
        "surface-dim": "#111220",
        "tertiary": "#ffb955",
        "secondary": "#a2e7ff",
        "background": "#111220",
        "inverse-primary": "#721ff6",
        "on-primary-fixed-variant": "#5700c8",
        "surface": "#111220",
        "surface-tint": "#d1bcff",
        "surface-container": "#1d1f2c",
      },
      fontFamily: {
        sans: ["Plus Jakarta Sans", "sans-serif"],
        headline: ["Plus Jakarta Sans", "sans-serif"],
        body: ["Plus Jakarta Sans", "sans-serif"],
        label: ["Plus Jakarta Sans", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        sm: "0.375rem",
        md: "0.5rem",
        lg: "0.75rem",
        xl: "1rem",
        "2xl": "1.25rem",
        "3xl": "1.5rem",
        full: "9999px",
      },
    },
  },
  plugins: [],
};

export default config;
