"""add_study_time_to_lecture

Revision ID: ba013cb0212b
Revises: 124827f23bd8
Create Date: 2026-05-25 18:53:20.643127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba013cb0212b'
down_revision: Union[str, None] = '124827f23bd8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lectures', sa.Column('study_time_seconds', sa.Integer(), server_default='0', nullable=True))
    op.drop_column('users', 'uuid')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('uuid', sa.VARCHAR(length=36), autoincrement=False, nullable=True))
    op.drop_column('lectures', 'study_time_seconds')
    # ### end Alembic commands ###
