"""sync_models_to_db

Revision ID: f1a1e6dde3fe
Revises: 004
Create Date: 2026-04-01 17:43:16.174608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f1a1e6dde3fe'
down_revision: Union[str, None] = '004'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_answer_timelines_attempt_id'), table_name='answer_timelines')
    op.create_unique_constraint(None, 'answer_timelines', ['attempt_id'])
    op.add_column('learning_patterns', sa.Column('exam_date', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_performance_sessions_completed_at'), 'performance_sessions', ['completed_at'], unique=False)
    op.create_index(op.f('ix_performance_sessions_started_at'), 'performance_sessions', ['started_at'], unique=False)
    op.drop_column('performance_sessions', 'exam_date')
    op.create_index(op.f('ix_question_attempts_created_at'), 'question_attempts', ['created_at'], unique=False)
    op.create_index(op.f('ix_question_attempts_question_id'), 'question_attempts', ['question_id'], unique=False)
    op.create_index(op.f('ix_question_attempts_session_id'), 'question_attempts', ['session_id'], unique=False)
    op.create_index(op.f('ix_results_share_token'), 'results', ['share_token'], unique=True)
    op.drop_index(op.f('ix_student_ai_insights_student_id'), table_name='student_ai_insights')
    op.create_index('ix_ai_insights_student_current', 'student_ai_insights', ['student_id', 'is_current'], unique=False)
    op.create_unique_constraint('uq_co_failure_student_pair', 'topic_co_failures', ['student_id', 'topic_a', 'topic_b'])
    # users.id type change (INTEGER -> String) skipped — would break existing FK data
    # Recreate email index as unique (drop old non-unique, add unique)
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.drop_index('ix_users_email', table_name='users')
    op.create_index('ix_users_email', 'users', ['email'], unique=True)
    op.alter_column('weak_points', 'decay_rate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Integer(),
               existing_nullable=True,
               postgresql_using='decay_rate::integer')
    op.create_unique_constraint('uq_weak_point_student_topic', 'weak_points', ['student_id', 'topic'])
    op.drop_index(op.f('ix_weekly_quiz_assignments_week_start'), table_name='weekly_quiz_assignments')
    op.create_index('ix_weekly_quiz_student_week_status', 'weekly_quiz_assignments', ['student_id', 'week_start', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_weekly_quiz_student_week_status', table_name='weekly_quiz_assignments')
    op.create_index(op.f('ix_weekly_quiz_assignments_week_start'), 'weekly_quiz_assignments', ['week_start'], unique=False)
    op.drop_constraint('uq_weak_point_student_topic', 'weak_points', type_='unique')
    op.alter_column('weak_points', 'decay_rate',
               existing_type=sa.Integer(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'id',
               existing_type=sa.String(length=36),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_constraint('uq_co_failure_student_pair', 'topic_co_failures', type_='unique')
    op.drop_index('ix_ai_insights_student_current', table_name='student_ai_insights')
    op.create_index(op.f('ix_student_ai_insights_student_id'), 'student_ai_insights', ['student_id'], unique=False)
    op.drop_index(op.f('ix_results_share_token'), table_name='results')
    op.drop_index(op.f('ix_question_attempts_session_id'), table_name='question_attempts')
    op.drop_index(op.f('ix_question_attempts_question_id'), table_name='question_attempts')
    op.drop_index(op.f('ix_question_attempts_created_at'), table_name='question_attempts')
    op.add_column('performance_sessions', sa.Column('exam_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_performance_sessions_started_at'), table_name='performance_sessions')
    op.drop_index(op.f('ix_performance_sessions_completed_at'), table_name='performance_sessions')
    op.drop_column('learning_patterns', 'exam_date')
    op.drop_constraint(None, 'answer_timelines', type_='unique')
    op.create_index(op.f('ix_answer_timelines_attempt_id'), 'answer_timelines', ['attempt_id'], unique=False)
    # ### end Alembic commands ###
